Remove percent-encoding of cookies
algesten/ureq pull request #338
Opened 2021-02-27 13:21 UTC by lukasschlueter

Fixes #315 

NOTE: This might be breaking for some people that might have relied on additional client-side percent-encoding, but I'd classify this as a bug-fix

2021-02-27 13:23 UTC, lukasschlueter commented on Cargo.toml
> -cookie = { version = "0.14", features = ["percent-encode"], optional = true}
This feature is no longer needed (but still enabled by `cookie_store`, see https://github.com/pfernie/cookie_store/issues/13)

2021-02-28 09:24 UTC, algesten commented
Looks ok. Can we add a test for this? Something where the server responds with a cookie containing strange values and we send the exact thing back?

2021-02-28 17:53 UTC, jsha requested changes
In #315 I mentioned that the cookie name in question seems to be in violation of the cookie RFC (6625) because it contains invalid characters. I'd like to combine the removal of percent-encode with the addition of a filter to require that cookie names meet the definition of `token`. Are you willing to add that to this PR?

2021-03-24 19:09 UTC, algesten commented
Closed by #353

2021-03-24 19:09 UTC, closed without merging