Add tcp no_delay option
algesten/ureq pull request #465
Opened 2022-01-05 20:53 UTC by daniel0611

Closes #390.

Defaults to set no_delay but can be overwritten by calling `agent.no_delay(false)`.

2022-01-05 22:02 UTC, algesten commented
Hi! Thanks for this PR – looks great. 

I guess it's somewhat dodgy to change the default value, but I can't see how it would break any existing code and we have precedence in all other http libraries. 

Let's merge!

Thanks!

2022-01-05 22:04 UTC, algesten commented
@jsha any comments on the API?

2022-01-06 04:42 UTC, jsha commented
API looks good. It's not clear to me why the internal value is an Option<bool> rather than a bool?

2022-01-06 06:24 UTC, algesten requested changes

2022-01-06 06:24 UTC, algesten commented on src/agent.rs
> +                no_delay: None,
let's change to straight up bool.

2022-01-06 08:10 UTC, daniel0611 commented
Sorry, can't remember why I went with an Option. Makes no sense to me now either. I changed it to `bool` now.

2022-01-06 14:54 UTC, jsha approved these changes

2022-01-06 22:15 UTC, algesten approved these changes

2022-01-06 22:22 UTC, merged