Feature/http compat
algesten/ureq pull request #520
Opened 2022-05-21 23:35 UTC by nicholastmosher

Here's my first attempt at solving #501, I'd like to hear your opinions on it. Unfortunately I wasn't able to run this locally because something about the build was failing for me. This introduces an `http-compat` feature which pulls in the optional dependencies on `http` and `bytes`. It adds a new `UreqBody` type like was mentioned in #501, and has a few basic conversions (though we'll probably want to support more).

2022-05-22 11:16 UTC, algesten requested changes
Thanks for this!

It looks pretty good. With ureq I steered clear of `Bytes`, because I want to use the "built in" standards instead. If we are to introduce Bytes, I'd like to see a separate discussion about it and introduce it across the board, not just in the http compat.

So if we change the internal representation to `Vec<u8>` I think we're almost there. Maybe there are a couple of more `From` we can do for the body.

2022-05-22 15:54 UTC, nicholastmosher commented on flake.nix
> +}
Sure thing, I had intended that to be temporary while this was in draft, I use NixOS and it's the easiest way to pull in dependencies. Rebased it out of this PR

2022-05-22 15:55 UTC, nicholastmosher commented on Cargo.toml
> +bytes = { version = "1.1.0", optional = true }
I removed it per your other comment about removing `Bytes` for now

2022-05-22 17:49 UTC, algesten commented
Looking good!

You need to run `cargo fmt`.

I'm wondering whether `UreqBody` should have a second field for a proposed mime type?

* `From<String>` -> `text/plain; charset=utf-8`
* `From<Vec<u8>>` -> `application/octet-stream`
* `From<[u8]>` -> `application/octet-stream`

This mime type would be a fallback in case the user doesn't set an explicit value in the headers.

Thoughts?

2022-05-26 23:47 UTC, nicholastmosher commented
Sounds like a good idea, I went ahead and added that. I also realized I had forgotten to copy over the headers from the http::Request before.

Also while implementing this I think I have found a flaw in the ureq headers handling. I believe that http headers may have multiple headers with the same name, but the API for getting headers out of a `ureq::Response` is `response.header(name: &str)`, which implies there is only one header value by that name.

2023-10-10 18:39 UTC, MarijnS95 commented
Looks like this can be closed as superseded by #591?

2023-10-11 08:40 UTC, closed without merging

2023-10-11 08:40 UTC, algesten commented
@MarijnS95 very true. Thanks!