add HTTPS proxy support
algesten/ureq pull request #544
Opened 2022-09-28 14:15 UTC by puffi

The addition of HTTPS proxy support requires a change of the `connect_host` interface. The return type is changed, but since this is only used internally in this one file and has visibility pub(crate) this should not be a breaking change.

The TCP Stream now gets wrapped inside the connect_host function which makes the `from_tcp_stream` function of Stream unused.

Signed-off-by: Mira Limbeck <m.limbeck@proxmox.com>

2022-09-29 20:13 UTC, algesten commented
Would you mind rebasing off latest main? So we can see a clean test run.

2022-09-30 13:32 UTC, puffi commented
It should be rebased now, at least I see the force-push mentioned here.

Sorry, first time doing that here on Github.

2022-10-03 09:13 UTC, puffi commented
Sorry about that, it seems to be the unused `from_tcp_stream` function I left in which leads to the errors.
Do you want me to remove it from the source?

2022-10-03 12:52 UTC, algesten commented
@puffi Yeah, that be great. Makes it compile cleanly in the CI. 👍

2022-10-15 17:56 UTC, algesten commented
@jsha what do you think about the extra `Box<dyn>` indirection we get in this PR?

I think the PR looks fine overall, but a bit concerned about this.

2022-12-03 21:21 UTC, jsha requested changes
I think the `Box<dyn>` indirection is not a big deal - we already take a `Box<dyn>` (for good reason) in `stream_to_reader`. This introduces a second level of dynamic dispatch, and it would be nice to collapse them into a single level.

In terms of code structure, we have `connect_http` and `connect_https`, which both call `connect_host`. For the latter, it then wraps the result of `connect_host` in an HTTPS stream. Coincidentally (or not), this is where the existing layer of dynamic dispatch is introduced. It would be nice for the "HTTPS proxy" code path to go through `connect_https` as well, which would require some code reorganization. Conceptually we have:

 - direct connect, plaintext
 - direct connect, HTTPS
 - proxy, plaintext
 - proxy, HTTPS

It would be nice if we could have a set of functions that reflect that more explicitly.

2022-12-03 21:21 UTC, jsha commented on src/stream.rs
> +            let mut s;
I'd love to have a more descriptive variable name here, and a type annotation. With the current code, the reader has to read _forward_ in the code to figure out what type `s` is.

2022-12-03 21:21 UTC, jsha commented on src/stream.rs
> +            write!(s, "{}", proxy.connect(hostname, port)).unwrap();
I see that we already have this `.unwrap()`, but it would be nice to cleanup while we're here to use a `?` instead.

2022-12-03 21:21 UTC, jsha commented on src/stream.rs
> +/// If successful, returns a `Box<dyn ReadWrite>` around a TcpStream and the remote address it is connected to.
This comment is not strictly accurate, since this could now be wrapping a TcpStream _or_ a TLS stream.

2023-05-08 13:30 UTC, closed without merging

2024-02-04 00:04 UTC, DanGould commented
Any reason this shouldn't be re-opened? I started implementing the same functionality before I found this PR. I ran into a small issue where we're calling [`Response::do_from_stream` now](https://github.com/algesten/ureq/blob/2300a5b3787b1ac800314dc47f075f4850026bb3/src/stream.rs#L458) which takes ownership of the tls_stream that we ultimately need to return, and there's no easy way to clone a `Box<dyn ReadWrite>` returned from `tls_conf.connect(..)`, but it seems surmountable.