Auto detect proxy from environments
algesten/ureq pull request #649
Opened 2023-08-11 07:22 UTC by dojiong

solve #322 
----
Just like reqwest, auto detect proxy from `ALL_PROXY`/`HTTPS_PROXY`/`HTTP_PROXY` [reqwest::proxy.rs](https://github.com/seanmonstar/reqwest/blob/master/src/proxy.rs#L834)

Add `AgentBuilder::no_proxy` if someone don't want to use system's proxy

2023-08-11 07:28 UTC, algesten requested changes

2023-08-11 07:28 UTC, algesten commented on src/proxy.rs
> +
I like this. Nice!

2023-08-11 07:28 UTC, algesten commented on src/agent.rs
> +        }
I don't think this is the place to do this. It changes the default behavior (which is to not pick up any proxy settings), and that might be a breaking change for some users (thus requiring a major version bump).

I think we need to feature-flag this to be opt-in behavior. Or am I being overly cautious?

2023-08-11 07:32 UTC, dojiong commented on src/agent.rs
> +        }
I think that's fine to change this default behavior, the user who use these envs is known the traffic will in proxy, it's the default behavior in many libraries or tools.

2023-08-11 08:35 UTC, Narsil commented on src/agent.rs
> +        }
I think you're correct. This is enabling very bad behavior. 
`curl` and `python.requests` accept this.. but this is VERY bad in my opinion, just made a small proof of concept, I can intercept all traffic...

2023-08-11 08:50 UTC, Narsil commented on src/agent.rs
> +        }
Just for fun: https://github.com/Narsil/test_proxy.

Seems crazy now that I'm aware of it...

2023-08-11 08:51 UTC, Narsil commented on src/agent.rs
> +        }
Also `requests` had until very recently a very nice flag to disable certs... https://github.com/psf/requests/issues/6071 good combo.

2023-08-11 09:17 UTC, dojiong commented on src/agent.rs
> +        }
> Just for fun: https://github.com/Narsil/test_proxy.

that's what a proxy do, sniffe or cache or vpn.

> Also requests had until very recently a very nice flag to disable certs... https://github.com/psf/requests/issues/6071 good combo.

this issuse is a empty-env bug(should not disable verify on empty env, because empty-config is easy to misuse), it does not indicates CURL_CA_BUNDLE is insecure, it's really useful in some cases.

2023-08-11 09:21 UTC, dojiong commented on src/agent.rs
> +        }
proxy env is a simple way to redirect traffic when it's hard to setup a global vpn

2023-08-11 09:33 UTC, Narsil commented on src/agent.rs
> +        }
https://github.com/seanmonstar/reqwest/issues/1937

2023-09-30 08:06 UTC, algesten approved these changes

2023-09-30 08:06 UTC, merged

2023-09-30 08:08 UTC, algesten commented on src/agent.rs
> +        }
On balance I'm not swayed by having this turned on by default. My main problem is that it breaks backwards compatibility of ureq. For now, this defaults to off.

2023-09-30 08:08 UTC, algesten commented
Thanks for the work in this PR!